### ISSUE TITLE
Firefox 4 Support

### ISSUE THREAD

**Issue by PatrickTulskie** [glee/glee#190]
Rather that ask on closed tickets, I figured I'd start a new ticket...

So, what needs to be done in order to get Firefox 4 support for Gleebox?  I know a few betas ago, it was working fine with the exception of some href security warnings on sites like Facebook.  In the latest FF4 beta 10, it doesn't appear at all.

I started working on getting the build.sh script to work for building a FF .xpi on my OS X machine.  I'd like to get the discussion started to find out what else needs to be done for Firefox 4 support.

If I can get a list of stuff that needs to be fixed or updated then I can start working on it, or perhaps others can pick items off the list as well.  Just looking to get the discussion started.

Full Disclosure: I've never built my own Firefox Extension before.

**Comment by ddaanet** [comment]
I am getting away from Chrome because of concerns of privacy, lack of trust in Google, and their questionable behaviour regarding (VoiceSearch)[https://www.privateinternetaccess.com/blog/2015/06/google-chrome-listening-in-to-your-room-shows-the-importance-of-privacy-defense-in-depth/].

Gleebox has become an essential tool for me. I will donate $25 when it becomes supported on Firefox again.
